# Generated by Django 4.1.7 on 2023-03-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pw', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'web',
                'managed': False,
            },
        ),
    ]
