# Generated by Django 4.1.7 on 2023-03-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bunyang'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillaSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('시군구', models.TextField(blank=True, null=True)),
                ('지역코드', models.BigIntegerField(blank=True, null=True)),
                ('법정동', models.TextField(blank=True, null=True)),
                ('단지명', models.TextField(blank=True, null=True)),
                ('전용면적', models.FloatField(blank=True, null=True)),
                ('거래금액', models.FloatField(blank=True, null=True)),
                ('층', models.TextField(blank=True, null=True)),
                ('건축년도', models.FloatField(blank=True, null=True)),
                ('년', models.BigIntegerField(blank=True, null=True)),
                ('월', models.BigIntegerField(blank=True, null=True)),
                ('광역시도', models.TextField(blank=True, null=True)),
                ('시자치구', models.TextField(blank=True, null=True)),
                ('전용', models.FloatField(blank=True, null=True)),
                ('대지권면적', models.FloatField(blank=True, null=True)),
                ('기준월', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'villa_sale',
                'managed': False,
            },
        ),
    ]
