# Generated by Django 4.1.7 on 2023-04-08 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rentvilla'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rentvilla',
            table='villa_rent',
        ),
    ]
